spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackgame?serverTimezone=Asia/Seoul
    username: #USER1
    password: #비밀번호
  jpa:
    hibernate:
      ddl-auto: update    # 처음엔 update / 운영은 validate
    show-sql: true        # 콘솔에 SQL 보이기
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB #예시
      max-request-size: 10MB #예시
